### ISSUE TITLE
SelectSitemapDialog doesn't handle configuration changes

### ISSUE THREAD

**Issue by dereulenspiegel** [dereulenspiegel/HABSweetie#18]
When the SelectSitemapDialog is shown the App crashes after a configuration change. Also the dialog can be shown again if a sitemap was selected successfull, but the device is rotated afterwards.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.akuz.android.openhab/de.akuz.android.openhab.ui.PageActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2185)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2210)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3638)
at android.app.ActivityThread.access$700(ActivityThread.java:142)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1214)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4931)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:330)
at android.widget.ListView.setAdapter(ListView.java:460)
at de.akuz.android.openhab.ui.ChooseSitemapDialogFragment.onCreateDialog(ChooseSitemapDialogFragment.java:76)
at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:829)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1802)
at android.app.Activity.performCreate(Activity.java:5011)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2139)
... 12 more
```

**Comment by dereulenspiegel** [comment]
Should be finally fixed-
